### ISSUE TITLE
aria-label creating issue when it gets re-added after a while

### ISSUE THREAD

**Issue by tanmayrajani** [tanmayrajani/notifications-preview-github#10]
Experienced this strange behaviour where Github somehow re-adds the `aria-label` attribute back after a while (which was removed by extension to disable native tooltip) but it doesn't re-add the `tootipped` classes.. which causes it to look something like this:

![issue-hover-aria-label](https://user-images.githubusercontent.com/8295888/29749263-1c607680-8b45-11e7-9134-36dbcce71f32.png)

**Comment by tanmayrajani** [comment]
fixed by clearing the `aria-label` instead of removing the attribute in efcaec1.

btw @bfred-it, Any better way to solve it?

**Comment by bfred-it** [comment]
My rewrite for #9 fixed it
