### ISSUE TITLE
Linkify the header of each notification group

### ISSUE THREAD

**Issue by darkred** [tanmayrajani/notifications-preview-github#106]
Greetings

I'd like to make a feature suggestion regarding the popup content:
**to linkify the header of each notification group**, 
i.e. linkify:
![2020-08-02_171656](https://user-images.githubusercontent.com/723651/89125059-675cfa00-d4e4-11ea-8c2a-be6c0c906ab6.jpg)

This is a very convenient 'Refined GitHub' extension feature:
> `linkify-notification-repository-header source, [screenshot](https://user-images.githubusercontent.com/1402241/80849887-81531c00-8c19-11ea-8777-7294ce318630.png)
> Linkifies the header of each notification group (when grouped by repository).

Thank you

**Comment by tanmayrajani** [comment]
Sounds good to me. Would be great if you want to try out building the same?

**Comment by fregante** [comment]
This is how it's done in Refined GitHub: https://github.com/sindresorhus/refined-github/blob/master/source/features/linkify-notification-repository-header.tsx

**Comment by darkred** [comment]
I've made PR #108 
I hope you like my attempt, I tried to stay close to RG's code.
