### ISSUE TITLE
Use Badging API if available to update the app badge

### ISSUE THREAD

**Issue by karlhorky** [tanmayrajani/notifications-preview-github#115]
Hi there, thanks for this extension, really cool!

Using [the Badging API](https://web.dev/badging-api/) ([spec](https://w3c.github.io/badging/), shipped to stable Chrome in April 2020), `navigator.setAppBadge(notificationsCount)` and `navigator.clearAppBadge()` can set and clear the application badge that shows up with PWA and pseudo-PWA windows (create a pseudo-PWA with three dots menu -> More Tools -> Create Shortcut... -> Open as window).

On macOS this looks like this in the Dock:

![Screen Shot 2020-12-08 at 15 11 36](https://user-images.githubusercontent.com/1935696/101494645-e61ce480-3967-11eb-9f10-f457b39d935a.png)

**Comment by fregante** [comment]
This extension only works when the tab is visible, so the badge wouldn’t be updated if the window is minimized. 
You might want to ask this in https://github.com/sindresorhus/notifier-for-github

**Comment by karlhorky** [comment]
Ah, thanks for the tip! Opened a new issue over there: https://github.com/sindresorhus/notifier-for-github/issues/235
