### ISSUE TITLE
Support for official Dark Mode

### ISSUE THREAD

**Issue by jerone** [tanmayrajani/notifications-preview-github#116]
GitHub introduced a [dark mode option](https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/#dark-mode).

It looks like there are a few colors hard-coded to the light mode:

![](https://user-images.githubusercontent.com/55841/101784643-13020080-3afc-11eb-92ac-b416a4f3620d.png)

**Comment by tanmayrajani** [comment]
Thank you for bringing this to notice! Working on a fix.

**Comment by yakov116** [comment]
That was fast! Thanks

**Comment by tanmayrajani** [comment]
Facing an error publishing to chrome because of their policy changes. Working on it. Firefox should have the update soon.

**Comment by jerone** [comment]
Awesome work, thank you 👍
