### ISSUE TITLE
The popup to close when you move the mouse away from its area

### ISSUE THREAD

**Issue by darkred** [tanmayrajani/notifications-preview-github#123]
Currently, once you mouseover the notification counter and the popup appears,
the only way to close it is to click outside the popup.

My suggestion is the popup to close when you move the mouse away from its area.
In other words, the popup to remain visible only while the cursor is near its area.

Thank you

(extension 21.3.9 in Chrome 89/Firefox 87)

**Comment by tanmayrajani** [comment]
imo we should keep it as much similar to other popovers nearby.. and they all close on clicking outside.. I know that they also open on click and not hover but we need to keep the click for visiting github.com/notifications so what we have currently seems the best way I guess?

@fregante WDYT?

**Comment by fregante** [comment]
The problem is ensuring that it doesn’t close involuntary. You don’t want it to close if you move 5px away from the icon. That’s probably why it is the way it is.

**Comment by darkred** [comment]
> it’d break expectations of existing users and its not worth adding an option for it.

What about adding it as an option that is disabled by default?

With the current behavior, it happens to me too many times that I open it by mistake.

Personally, I would definitely prefer to have to reopen it via hover, than having to click outside to close it every time.
In the long term, I believe I could quickly "learn" to maintain the cursor near the icon/popup, 
to keep the popup open for as long as needed.

**Comment by darkred** [comment]
I made PR #125
