### ISSUE TITLE
Store publish not working?

### ISSUE THREAD

**Issue by tanmayrajani** [tanmayrajani/notifications-preview-github#131]
I published a release yesterday with a fix for #130 but it doesn't seem to have reached chrome/firefox stores. Not sure what's wrong.. 

cc @fregante if you have any idea, could you please look into?

**Comment by fregante** [comment]
Releases are done via the actions tab, not by creating releases manually. The release and tag should be deleted and then done via the Release action.

**Comment by tanmayrajani** [comment]
thanks @fregante, I forgot 🤦‍♂️ 
 
also, getting `"{\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"Bad Request\"\n}"` in chrome, whereas firefox succeeded after first error (needed to accept ToC)

**Comment by tanmayrajani** [comment]
however, chrome upload succeeded despite getting that error :)

**Comment by tanmayrajani** [comment]
it shows updated version in chrome developer dashboard.. but on the webstore, it's still old version 😐

**Comment by tanmayrajani** [comment]
@fregante should we renew client ID, secret etc as mentioned in https://github.com/fregante/chrome-webstore-upload-cli/issues/36 for the time being?

**Comment by fregante** [comment]
But that's strange, invalid grant means that the token is wrong, so yes, it's probably best to follow the guide again.

**Comment by tanmayrajani** [comment]
@fregante sure, I'll take a look at this soonish

Also, Firefox asked for source-code upload (you might be getting emails too I guess). I provided it manually.. but I was wondering whether this is something that can be done via github action too

**Comment by fregante** [comment]
> you might be getting emails too I guess

Yes, AMO is really annoying.

Blocked by:

- https://github.com/mozilla/sign-addon/issues/409

Technically there's an API endpoint now but no libraries for it

**Comment by fregante** [comment]
Ping @tanmayrajani could you generate new keys with the guide at:

https://github.com/fregante/chrome-webstore-upload-keys#how-to-generate-google-api-keys
