### ISSUE TITLE
Global navigation update support

### ISSUE THREAD

**Issue by mustafaozhan** [tanmayrajani/notifications-preview-github#143]
Github released today `Global navigation update` it is currently in public beta, you can try by enabling the feature preview.

Unfortunately neither the `notification count` nor the `preview` of the notifications when you let mouse on notification area are working with new `Global navigation update`.

**Comment by tanmayrajani** [comment]
Keeping this open for pending things i.e. notification count and a fix in positioning

**Comment by tanmayrajani** [comment]
@mustafaozhan thanks for reporting this, I've made it work for the preview popover, however the count and positioning needs some work which we can get to later

**Comment by mustafaozhan** [comment]
@tanmayrajani thank you! That was a quick one 🙂 I confirm the `preview popover` is working in the latest version.

**Comment by silverwind** [comment]
Having that count back would be awesome. I depend on it 😆.

**Comment by fregante** [comment]
- count tracked in https://github.com/tanmayrajani/notifications-preview-github/issues/146
