### ISSUE TITLE
`npm install` results in 10 GB inside 'node_modules' folder

### ISSUE THREAD

**Issue by darkred** [tanmayrajani/notifications-preview-github#151]
After cloning the repo and entering `npm install` it results in 10 GB 'node_modules' folder.
This is made up by various `rust` subfolders in `@parcel` folder which all contain (among other files) the (binary) same 8 "parcel-node-bindings.darwin-*.node" files, each set of which is 262 MB in total: 

```log
parcel-node-bindings.darwin-arm64.node
parcel-node-bindings.darwin-x64.node
parcel-node-bindings.linux-arm-gnueabihf.node
parcel-node-bindings.linux-arm64-gnu.node
parcel-node-bindings.linux-arm64-musl.node
parcel-node-bindings.linux-x64-gnu.node
parcel-node-bindings.linux-x64-musl.node
parcel-node-bindings.win32-x64-msvc.node
```

<details>
<summary>Screenshots:</summary>

![2024-08-07_225622](https://github.com/user-attachments/assets/04b55c38-0b84-485c-a72c-5f5c54d5f4ca)
![2024-08-07_224944](https://github.com/user-attachments/assets/b1f0e320-6282-44d8-84cd-aa474e75d94c)
![2024-08-07_223146](https://github.com/user-attachments/assets/a8156f1b-2392-4af7-8c7e-8c8c83ac515d)
</details>

This is not a problem per se, but can be if you have limited disk space.

Using Node v22.6.0, npm 10.8.2 with Windows 11 x64.

**Comment by fregante** [comment]
Nothing can be done 🤷‍♂️ devDependencies are always huge, especially bundlers
