### ISSUE TITLE
Preload and preemptively load

### ISSUE THREAD

**Issue by bfred-it** [tanmayrajani/notifications-preview-github#17]
Should it regularly **preload the notifications** so that they are ready when you hover? Having to wait for a page to load almost defeats the purpose since it only saves the 300ms between `mouseenter` and `click`

**Comment by tanmayrajani** [comment]
Sure, it would be great if we preload the notifications. I agree, it kinda defeats the purpose..

**Comment by bfred-it** [comment]
Instant noodles!

![2 fast 4 furious](https://user-images.githubusercontent.com/1402241/30051265-8d41bdfc-924b-11e7-9dee-73b5bb7bc838.gif)

Since this is now instant (unless you catch an ongoing fetch), maybe it should no longer be a modal, but it should automatically close on mouseleave.
