### ISSUE TITLE
Disregard GitHub's UI status and try loading on every mouseenter

### ISSUE THREAD

**Issue by bfred-it** [tanmayrajani/notifications-preview-github#18]
I've found that the icon may not be up to date. For example when the computer goes to sleep without notifications and it wakes up later; the icon won't have had time to update yet and NPG won't open. So maybe it makes sense to **run `openPopup` whether `.unread` is there or not.**

**Comment by tanmayrajani** [comment]
Good point that, even I have encountered issues with the bell icon not knowing about new notifications when it didn't have any notifications previously and remained in a stale tab for a long time. We can probably show something like no unread notifications message when no notifications!
