### ISSUE TITLE
Mark all as read

### ISSUE THREAD

**Issue by fregante** [tanmayrajani/notifications-preview-github#22]
There's no way to mark all as read. Adding the button will make it look less balanced, so we might need to [get creative.](https://www.youtube.com/watch?v=9C_HReR_McQ)

**Comment by bfred-it** [comment]
Perhaps:

<img width="133" alt="screen shot 2017-09-05 at 15 16 22" src="https://user-images.githubusercontent.com/1402241/30051694-326f4c3a-924d-11e7-90d5-8511b4684d63.png">

Even if it's confusing, it should still trigger the confirmation modal, so not a big deal.

**Comment by tanmayrajani** [comment]
A tooltip should probably help initially if it's a bit confusing. 

Also, this won't conflict with what refined-github has on notifications page (mark all as read button) right? (I mean, I don't know refined-github features that much so just confirming..)

**Comment by bfred-it** [comment]
No, that Refined GitHub event listener should only work on the notifications page; this extension is disabled on that page 👍

**Comment by tjx666** [comment]
I implement it in my modified version: https://github.com/tjx666/github-notifications-preview/tree/main

**Comment by fregante** [comment]
@tjx666 if you prefer to contribute here, I'd be happy to merge your PRs (even if they rewrite the entire extension from scratch) and publish releases. I have now publishing rights to the Chrome Store

**Comment by tjx666** [comment]
@fregante https://github.com/tanmayrajani/notifications-preview-github/pull/152
