### ISSUE TITLE
Doesn't work on responsive pages (like the new Dashboard beta)

### ISSUE THREAD

**Issue by bfred-it** [tanmayrajani/notifications-preview-github#47]
On these pages, the extension is only visible in windows smaller than 1012px because `notifications-preview-github` is only applied to one of the two bells in the dom of the page.

https://github.com/explore
https://github.com/marketplace
https://github.com (with the new Dashboard beta)

**Comment by tanmayrajani** [comment]
Strange! I don't even see the count (of notifications) there..

**Comment by Keith94** [comment]
So, is a fix possible?

**Comment by bfred-it** [comment]
Yes, it needs to be added to both the elements
