### ISSUE TITLE
Notification popup will do nothing if on the that page already

### ISSUE THREAD

**Issue by yakov116** [tanmayrajani/notifications-preview-github#50]
![image](https://user-images.githubusercontent.com/16872793/31896041-c3a17c38-b7e0-11e7-8cee-1ba258d9799d.png)

**Comment by bfred-it** [comment]
Can you write a comment here? I'll keep this tab open

**Comment by yakov116** [comment]
@bfred-it like this?

**Comment by bfred-it** [comment]
Yes. It worked for me, when I clicked it it scrolled to your comment, because its link was:

```
https://github.com/tanmayrajani/notifications-preview-github/issues/50#issuecomment-338695710
```

**Comment by yakov116** [comment]
did the notification go away?

**Comment by bfred-it** [comment]
No, I think I had to click on the backdrop to close it.

I'm having a hard time to come up with clever ways to detect this:

- onclick + [not shift/alt/cmd/ctrl-click](https://github.com/bfred-it/filter-altered-clicks)
- `hashchange` event
- onclick + href === currentUrl

They're not clever enough!!1

Thoughts 😅 

(yes, I'm bored)

**Comment by yakov116** [comment]
Can't detect from the url?

**Comment by tanmayrajani** [comment]
If I open the same page as the notification is pointing, shouldn't the notification just go away (unless I click within 3 seconds)?

**Comment by yakov116** [comment]
@tanmayrajani it should...

**Comment by laughedelic** [comment]
It does for me

**Comment by yakov116** [comment]
@laughedelic the page is not blocked by the backdrop?

**Comment by bfred-it** [comment]
Context: the gray backdrop is part of https://github.com/sindresorhus/refined-github/pull/735, so most people don't notice it, even if it is there.

**Comment by bfred-it** [comment]
I think I found the clever way: automatically close the popup when it leaves the viewport, via intersectionobserver. But... that may not always happen. 😋

**Comment by laughedelic** [comment]
I have Refined Github installed, but I don't the blurred background. 
When I'm already on the page and a new notification appears for that page I can click it, it will scroll to the new comment and the notification will disappear.
![screen shot 2017-10-23 at 17 52 36](https://user-images.githubusercontent.com/766656/31899187-4cdc6898-b81b-11e7-8f5d-4df001ff634c.png)

**Comment by bfred-it** [comment]
No the notification probably doesn't disappear, there should still be an invisible layer that will capture your first click and will actually close the dropdown.

You don't see the blurred background because https://github.com/sindresorhus/refined-github/pull/735 hasn't been merged yet and @yakov116 was trying out that PR.

**Comment by yakov116** [comment]
@bfred-it Yup! Not even on purpose LOL.

I by mistake merged that pull...

Glad we found the bug before the bug happened to the "masses"

**Comment by bfred-it** [comment]
Yeah the visible backdrop definitely surfaced some bugs on GitHub as I had mentioned on that PR.

**Comment by laughedelic** [comment]
Haha 😅  OK, then. Don't mind me.

**Comment by bfred-it** [comment]
PRs welcome to fix this issue though :)
