### ISSUE TITLE
Can we remove the console logging?

### ISSUE THREAD

**Issue by yakov116** [tanmayrajani/notifications-preview-github#52]
Is it possible to remove the log each time the request is sent?

![image](https://user-images.githubusercontent.com/16872793/32498959-28bc090c-c39f-11e7-8687-078c80b13683.png)

**Comment by bfred-it** [comment]
That's Chrome's XHR logging. You can disable it in the console.

**Comment by yakov116** [comment]
@bfred-it hmm ok I need them open for debugging other things...


Thanks
