### ISSUE TITLE
Update screenshot on AMO and Chrome Web Store

### ISSUE THREAD

**Issue by bfred-it** [tanmayrajani/notifications-preview-github#53]
https://chrome.google.com/webstore/developer/dashboard/

https://github.com/tanmayrajani/notifications-preview-github/blob/master/media/screenshot.png

**Comment by tanmayrajani** [comment]
Done. Updated. Thanks for reminding :)

**Comment by tanmayrajani** [comment]
I see the screenshot on AMO is old one too. Let's update that too.

**Comment by bfred-it** [comment]
Thanks for the reminder, :D changing now.

Are you on AMO? I can add you as a collab

**Comment by tanmayrajani** [comment]
Sure, my username is "tanmayrajani" on AMO.

**Comment by bfred-it** [comment]
Email needed:

<img width="635" alt="screen shot 2017-11-16 at 13 35 01" src="https://user-images.githubusercontent.com/1402241/32875442-f9019ca0-cad2-11e7-8576-967c685b4875.png">

**Comment by tanmayrajani** [comment]
rajani.tanmay@gmail.com

**Comment by bfred-it** [comment]
Done, thanks!
