### ISSUE TITLE
[Feature Request] Option to display Participating notifications only

### ISSUE THREAD

**Issue by PeterDaveHello** [tanmayrajani/notifications-preview-github#56]
This extension is really useful, but I personally just got too many notifications so I wonder if we can have an option to display participating notifications only?

Many thanks!

**Comment by tanmayrajani** [comment]
@PeterDaveHello Thanks for the feature request. 

Now you have the option to see only participating notifications. :clinking_glasses: (Note that it is unchecked by default.)

**Comment by PeterDaveHello** [comment]
Cool! I see the option now, but looks like I can't find a button to save this change, did I miss anything? Thanks again!

**Comment by tanmayrajani** [comment]
It saves automatically. You can go ahead and refresh your GitHub to start seeing only the participating notifications

**Comment by PeterDaveHello** [comment]
hmmmm, I'm not sure what's the problem behind mine because it didn't save it

**Comment by bfred-it** [comment]
Are you on Firefox?

**Comment by PeterDaveHello** [comment]
Yes!

**Comment by bfred-it** [comment]
Damn Firefox. There's a bug somewhere that's causing the settings not to be saved. Also in my other extension: https://github.com/bfred-it/github-issue-link-status/issues/12

Are you able to debug the extension's options page? Hopefully there's some error in the console if you just open the extension's debugger + the options page as shown here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging#Debugging_options_pages

**Comment by PeterDaveHello** [comment]
hmmm, nothing found in the debug console lol ... not familiar with extension things :(

**Comment by bfred-it** [comment]
Did you open the console as suggested by that page? You have to go to `about:debugging` first and open the console specific to this extension. Without your help I can't fix it because it always works for me.

**Comment by bfred-it** [comment]
Yeah, just follow the steps shown in the video in the first 6 seconds: https://youtu.be/BUMG-M8tFF4

Then select the "Console" tab and try to change the settings. You should see messages like "field saved", etc


![a](https://user-images.githubusercontent.com/1402241/36107023-769b10a2-104b-11e8-95bc-dca9fda28a3e.gif)

**Comment by PeterDaveHello** [comment]
Will try soon, sorry for the late response.

**Comment by PeterDaveHello** [comment]
It's odd that nothing appears there ... I'll find another clean installed Firefox and try again later, thanks.
