### ISSUE TITLE
Addon disappeared from AMO

### ISSUE THREAD

**Issue by jdreesen** [tanmayrajani/notifications-preview-github#61]
Somehow this awesome addon seems to have been disappeared from AMO and thus cannot be installed in Firefox anymore :(

The [link in the readme](https://addons.mozilla.org/en-US/firefox/addon/notifications-preview-github/) only shows "_Sorry, but we can't find anything at the address you entered_".

Could you please have a look whats wrong?

**Comment by tanmayrajani** [comment]
Yes, unfortunately they have removed it from AMO since they found an issue in our code. @bfred-it was looking into it.. I haven't got a chance to look into it. Maybe @bfred-it could fix this soon and we'll be up and running again!

**Comment by bfred-it** [comment]
Yep. AMO re-blocked the plugin for the same reason they blocked it initially, but then they agreed it didn't need to be blocked. I haven't had time to go on IRC again and discuss it. 

Just use this to install it on Firefox: https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/

**Comment by jdreesen** [comment]
Hmm, I'd prefer to install it directly, so I think I'll wait a while until you find some free time and hopefully resolve the issue (sadly, it doesn't sound like I can help anyhow!?).

**Comment by bfred-it** [comment]
Good luck!

**Comment by Keith94** [comment]
Here's an XPI that can be installed directly in Firefox. It's version 1.1.0 (latest at this time of writing).

[notifications-preview-github@tanmayrajani.github.io.xpi.zip](https://github.com/tanmayrajani/notifications-preview-github/files/2041393/notifications-preview-github.tanmayrajani.github.io.xpi.zip)

**Comment by tanmayrajani** [comment]
AMO has approved version 1.2.0 and is available now in their gallery: https://addons.mozilla.org/addon/notifications-preview-github/

**Comment by jdreesen** [comment]
This is awesome! I just installed this addon on my new Firefox profile <3
