### ISSUE TITLE
Hover Stopped Working

### ISSUE THREAD

**Issue by yakov116** [tanmayrajani/notifications-preview-github#62]
Dont know what changed

**Comment by tanmayrajani** [comment]
Was basically DOM changes by GitHub. Have fixed and drafted a new release. Should be available soon to everyone. 

- @bfred-it if you get time, can you please look into d40dfd1, not fully confident whether it's the best way to solve the problem..

Thanks for reporting, @yakov116

**Comment by yakov116** [comment]
@tanmayrajani your very welcome. I use this daily and almost forget that it's not a built in github feature!

Thanks again!!

**Comment by jdreesen** [comment]
I just installed `v1.2.0` from AMO and it works again, thx :)
