### ISSUE TITLE
Notification icon can't be clicked

### ISSUE THREAD

**Issue by Keith94** [tanmayrajani/notifications-preview-github#64]
When the preview panel opens when hovering the notification icon, the icon itself can't really be clicked accurately.

**Comment by jdreesen** [comment]
I noticed that, too.

**Comment by tanmayrajani** [comment]
'twas another by-product of DOM changes. Fixed. Should be available as next release i.e. `1.3.0` in couple hours.

Thanks for reporting, @Keith94, @jdreesen! :)

**Comment by jdreesen** [comment]
It works again for me in the latest version. Thx for the quick fix :)
