### ISSUE TITLE
Extension showing part of icons when no notifications are available

### ISSUE THREAD

**Issue by AnthonyLenglet** [tanmayrajani/notifications-preview-github#73]
As of today, the extension is showing part of icons underneath the bell when no notifications are available

![image](https://user-images.githubusercontent.com/36004334/63412681-8314e080-c3f8-11e9-86c9-2df4dd4df4ed.png)

**Comment by tanmayrajani** [comment]
Yes, thanks for the report, just noticed that too. I'll see if I can spare some time..

**Comment by tanmayrajani** [comment]
fixed in 5cd4d33
