### ISSUE TITLE
not showing feedback when using mark as read for an entire repo

### ISSUE THREAD

**Issue by AnthonyLenglet** [tanmayrajani/notifications-preview-github#76]
The ability to mark as read was fixed recently, though I remember there being visual feedback when I used to mark all as read for a repo.

in the notification page, it makes a text appear saying "Marked X notifications as read" and changes the background color to grey on all the notifications.

I know it does that second part when marking a single notification as read, so this case seems to be working fine.

**Comment by tanmayrajani** [comment]
Duplicate of #75.

Thanks for the report! Mark single notification as read was recently worked upon, mark as read for entire repo is pending and will be worked upon once I can spare some time. :) (also, goes without saying.. feel free to contribute!)

Cheers!

**Comment by AnthonyLenglet** [comment]
ok, thanks for the heads up !
I wasn't sure if "mark all as read" was talking about this case or a way to mark all the notification of all the repos as read
(if I can spare some time I would gladly help with this :D)

Thanks again !
