### ISSUE TITLE
Extension doesn't seem to work with new GitHub Notifications Beta

### ISSUE THREAD

**Issue by jack1142** [tanmayrajani/notifications-preview-github#79]
Hovering on notification icon does nothing.

**Comment by yakov116** [comment]
they updated every one its not longer beta.

im not managing LOL

**Comment by jack1142** [comment]
It's still beta, and I can still opt out, but that doesn't mean I want to 😛

**Comment by yakov116** [comment]
@jack1142 I agree this morning they enabled me (without me asking)

**Comment by tanmayrajani** [comment]
Hi guys, thank you for your interest in this, I am afraid I might not have enough time lately to work towards this.. feel free to contribute, thank you!

**Comment by fregante** [comment]
This is now available for Firefox users, but Chrome users will have to wait for #83
