### ISSUE TITLE
Chrome Store deployment failed

### ISSUE THREAD

**Issue by fregante** [tanmayrajani/notifications-preview-github#83]
https://travis-ci.org/github/tanmayrajani/notifications-preview-github/builds/667903724

```sh
$ cd extension && webstore upload --auto-publish
Response code 400 (Bad Request)
{
    "error": "invalid_grant",
    "error_description": "Bad Request"
}
```

I think that Chrome’s credentials (`REFRESH_TOKEN` `CLIENT_SECRET` `CLIENT_ID`) need to be updated .

---

Since I've been updating the deployment script to use GitHub Actions on my other extensions, let's set all of these ENVs directly there:

https://github.com/tanmayrajani/notifications-preview-github/settings/secrets

Get them from:
- Firefox: https://addons.mozilla.org/en-US/developers/addon/api/key/
- Chrome: https://github.com/DrewML/chrome-webstore-upload/blob/master/How%20to%20generate%20Google%20API%20keys.md

Demo:

<img width="1018" alt="secrets" src="https://user-images.githubusercontent.com/1402241/77961814-bc8cc300-72da-11ea-88ba-cd76670d2336.png">

**Comment by tanmayrajani** [comment]
I have added all three of them in the notifications-preview-github/settings/secrets. Should be good now. Let me know in case of anything else.

Also, thank you so much for doing this! :)

**Comment by fregante** [comment]
Did you also add the 2 for firefox?

How were the instructions for chrome? Were they completely clear and working? I  updated that document a couple of days ago

**Comment by tanmayrajani** [comment]
sorry, I somehow missed the email notification of this. I just added the firefox ones as well.

And, yes, instructions for chrome were definitely clear and working, I was done in no time.
