### ISSUE TITLE
Chrome Store rejected new versions (privacy info)

### ISSUE THREAD

**Issue by fregante** [tanmayrajani/notifications-preview-github#91]
> Publish condition not met: To publish your item, you must provide mandatory privacy information. This can be done in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole.

Related Refined GitHub issue, probably parts of it can be copied: https://github.com/sindresorhus/refined-github/issues/2685

@tanmayrajani  can you look into it?

**Comment by tanmayrajani** [comment]
![image](https://user-images.githubusercontent.com/8295888/78865865-0a809400-7a5c-11ea-8cbe-7f52fa26443f.png)

I'm guessing since we use npm modules, we _are_ using remote code? What should the justification be for that?

**Comment by fregante** [comment]
No we’re not using remote code 😃 
The code is packaged and sent to them in a zip file. By “remote” they mean “downloaded from the internet directly from the user’s computer”

**Comment by tanmayrajani** [comment]
oh right, makes sense :man_facepalming:. I have just submitted the request. It's in pending review now.

**Comment by tanmayrajani** [comment]
It's published! :clinking_glasses:

**Comment by fregante** [comment]
That was fast!

**Comment by fregante** [comment]
@tanmayrajani are you sure? Did you submit it? It still says this:

> Publish condition not met: To publish your item, you must provide mandatory privacy information in the new Developer

**Comment by tanmayrajani** [comment]
It's asking justification for storage.. weird that a few days ago that wasn't a field in the form, must be some new changes. Anyway, I'm mentioning that we need it for storing user preferences. Let me know in case of changes..

**Comment by fregante** [comment]
Heh, it's possible. Yes we use storage for the options

**Comment by tanmayrajani** [comment]
It got updated on the chrome store too, pretty fast!

**Comment by fregante** [comment]
Indeed, I see it now 🙌
