### ISSUE TITLE
Can't mark notifications as read

### ISSUE THREAD

**Issue by mmoayyed** [tanmayrajani/notifications-preview-github#93]
Browser console (Chrome: 80.0.3987.163 (Official Build) (64-bit)), upon clicking on the notification icon shows: 

```github-notifications-preview.js:538 Uncaught (in promise) TypeError: {} is not a function```

See:
![image](https://user-images.githubusercontent.com/1205228/78972897-120b7000-7b24-11ea-80ce-c1f7fdc431fe.png)

And:
![image](https://user-images.githubusercontent.com/1205228/78972999-3b2c0080-7b24-11ea-928e-65a3b478bbef.png)

Plugin Version: 20.4.5

PS Happy to submit a PR if I can.

**Comment by tanmayrajani** [comment]
Hi, thank you for submitting the issue. 

As you might know, we have recently worked to have very minimal support of beta notifications, all thanks to @fregante. Marking as read might not be supported just yet but hopefully we will get it to work in a near future. Feel free to contribute if you can :clinking_glasses:

**Comment by mmoayyed** [comment]
Thanks very much. I appreciate note, and will take a look to see if I might be able to provide a fix.

**Comment by fregante** [comment]
Indeed, the whole listener is build around the old notifications UI and needs to be rewritten for the new notifications.

**Comment by fregante** [comment]
This feature has been dropped for now. Moving issue to https://github.com/tanmayrajani/notifications-preview-github/issues/94
