### ISSUE TITLE
Restore "Mark as read"

### ISSUE THREAD

**Issue by fregante** [tanmayrajani/notifications-preview-github#94]
The feature was dropped in https://github.com/tanmayrajani/notifications-preview-github/commit/606d0227ad7d7693456af39d9ddc6fdd608ed4ad#diff-ee206f3e88c066917fc8b643bf8fa7a6 because it's incompatible with the new Notifications style and the button itself needs better CSS.

Help wanted to restore this feature.

Moved from https://github.com/tanmayrajani/notifications-preview-github/issues/93

**Comment by silverwind** [comment]
Should add both the "Done" and "Unsubscribe" buttons present on the notifications page.

**Comment by fregante** [comment]
It appears that if we load the missing script on the page, this will start working without extra JS code.

Missing script: https://github.githubassets.com/assets/notifications-v2-bootstrap-9ab1c3e0.js

We can get this URL from the notifications page and inject it only once the user opens the dropdown.

The second part of this issue would be to restore the buttons via CSS and fix their position/spacing.

**Comment by mallowigi** [comment]
I've opened a PR, please take a look.

**Comment by tanmayrajani** [comment]
This got implemented in #98. Closing.
