### ISSUE TITLE
Add drop-down menu listing recent notifications on Chrome bar

### ISSUE THREAD

**Issue by evandrocoan** [tanmayrajani/notifications-preview-github#97]
For example, this discourse plugin has it: https://meta.discourse.org/t/google-chrome-extension-for-discourse-notifications/34496

![image](https://user-images.githubusercontent.com/5332158/85143290-f6a59b00-b21f-11ea-8759-843b3f2068b4.png)

https://github.com/sindresorhus/notifier-for-github/issues/216

**Comment by jdreesen** [comment]
Have you even looked at the readme?

**Comment by evandrocoan** [comment]
Yes.

![image](https://user-images.githubusercontent.com/5332158/85210078-5df04780-b313-11ea-85bf-d2138de2ea7c.png)

**Comment by jdreesen** [comment]
But this is not what this add-on is about. It integrates into the GitHub bell and has no browser menu-bar icon.

**Comment by evandrocoan** [comment]
You do not like this feature or do not want to implement it, just say so and close this issue as won't fix instead of playing mind/word games.
